
[[runners]]
  name = "229 p2shop golang:builder-beta"
  url = "https://gitlab.p2shop.cn:8443/"
  token = "******"
  executor = "docker"
  cpus = 3.8
  environment = ["DOCKER_AUTH_CONFIG={\"auths\": {\"registry.elandsystems.cn:5000\": {\"auth\": \"******\"},\"registry.p2shop.com.cn\": {\"auth\": \"******\"}}}"]
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "docker:19.03.1"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/home/xiao.xinmiao/images/rtc:/builds/rtc","/home/xiao.xinmiao/images/golang-builder-beta/go:/builds/go", "/cache"]
    shm_size = 0
    wait_for_services_timeout = 30
    memory = "128m"
    memory_swap = "256m"
    memory_reservation = "64m"
    dns = ["8.8.8.8"]
    userns_mode = "host"
    cache_dir = "/builds/go"
    [runners.docker.sysctls]
       "net.ipv4.ip_forward" = "1"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.custom]
    run_exec = ""
