include: 
  - project: 'qa/gitlab-ci'
    ref: qa
    file: '/templates/go.gitlab-ci.yml'

variables:
  SERVICE_NAME: go-api-test1 #for example: product-api-pangpang-brand from   https://gitlab.p2shop.cn:8443/data/rtc-data/blob/qa/config.qa.yml
  # FOLDERNAME: ""  #for example: nomni/
  # GITLABWITCH: "msl" # msl srx srx-msl,for example: srx-msl:git on https://gitlab.srxcloud.com and images in https://ci.p2shop.com.cn
  # GOBUILDER: pangpanglabs/golang:builder-beta
  # GOTEST_REGISTRY: golang:1.12-alpine