
# 正式环境 用的是下面这句，而不是compose 
   # docker run -d -p 5000:5000 --memory-reservation="64M" --restart=always --name registry registry


version: '3'

services:
  registry:
    image: registry
    ports:
      - "443:443"
      - "5000:5000"
    volumes:
      - ./:/etc/docker/registry
      - registry-data:/var/lib/registry
    deploy:
      resources:
        reservations:
          cpus: '0.15'
          memory: 64M

volumes:
  registry-data:
